articles/urls.py
from django.conf.urls import include,url

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'articles'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^standings/$', views.standings, name='standings'),
    url(r'^articles/(?P<article_name_slug>[\w\-]+)/$', views.article, name='articles')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

fadeawayhoops/urls.py
from django.conf.urls import  include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    url(r'^', include('articles.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

articles/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import JSONField
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.fields import HStoreField
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings



# Create your models here.

def get_image_path(instance, filename):
    return os.path.join('photos', str(instance.id), filename)

class Metadata(models.Model):
    article_category = models.CharField(max_length=200)
    article_tags = models.TextField #turn into a list
    def __str__(self):
       return self.article_category

class Content(models.Model):

    article_title = models.CharField(max_length=200)
    article_tagline = models.CharField(max_length=200, null=True)
    article_author = models.CharField(max_length=2000)
    article_date = models.DateTimeField('date published')
    article_id = models.IntegerField
    article_text = models.TextField(max_length=20000, blank=True)
    article_image = models.FileField(null=True, blank=True)    # add image field to this later
    article_image2 = models.FileField(null=True, blank=True)    # add image field to this later
    slug = models.SlugField(unique=True,null=True,blank=True,max_length=255);
    metadata = models.ForeignKey('metadata', null=True)
    tags = models.CharField(max_length=300,blank=True,null=True)

    heading1 = models.CharField(max_length=250,null=True,blank=True);
    paragraph1 = models.TextField(max_length=20000,null=True,blank=True);

    heading2 = models.CharField(max_length=250,null=True,blank=True);
    paragraph2 = models.TextField(max_length=20000,null=True,blank=True);

    heading3 = models.CharField(max_length=250,null=True,blank=True);
    paragraph3 = models.TextField(max_length=20000,null=True,blank=True);

    heading4 = models.CharField(max_length=250,null=True,blank=True);
    paragraph4 = models.TextField(max_length=20000,null=True,blank=True);

    heading5 = models.CharField(max_length=250,null=True,blank=True);
    paragraph5 = models.TextField(max_length=20000,null=True,blank=True);

    heading6 = models.CharField(max_length=250,null=True,blank=True);
    paragraph6 = models.TextField(max_length=20000,null=True,blank=True);

    heading7 = models.CharField(max_length=250,null=True,blank=True);
    paragraph7 = models.TextField(max_length=20000,null=True,blank=True);

    heading8 = models.CharField(max_length=250,null=True,blank=True);
    paragraph8 = models.TextField(max_length=20000,null=True,blank=True);

    heading9 = models.CharField(max_length=250,null=True,blank=True);
    paragraph9 = models.TextField(max_length=20000,null=True,blank=True);

    heading10 = models.CharField(max_length=250,null=True,blank=True);
    paragraph10 = models.TextField(max_length=20000,null=True,blank=True);

    heading11 = models.CharField(max_length=250,null=True,blank=True);
    paragraph11 = models.TextField(max_length=20000,null=True,blank=True);

    heading12 = models.CharField(max_length=250,null=True,blank=True);
    paragraph12 = models.TextField(max_length=20000,null=True,blank=True);

    heading13 = models.CharField(max_length=250,null=True,blank=True);
    paragraph13 = models.TextField(max_length=20000,null=True,blank=True);

    heading14 = models.CharField(max_length=250,null=True,blank=True);
    paragraph14 = models.TextField(max_length=20000,null=True,blank=True);

    heading15 = models.CharField(max_length=250,null=True,blank=True);
    paragraph15 = models.TextField(max_length=20000,null=True,blank=True);

    heading16 = models.CharField(max_length=250,null=True,blank=True);
    paragraph16 = models.TextField(max_length=20000,null=True,blank=True);

    heading17 = models.CharField(max_length=250,null=True,blank=True);
    paragraph17 = models.TextField(max_length=20000,null=True,blank=True);




    def save(self, *args, **kwargs):
                # Uncomment if you don't want the slug to change every time the name changes
                #if self.id is None:
                        #self.slug = slugify(self.name)
            self.slug = slugify(self.article_title)
            super(Content, self).save(*args, **kwargs)

    def __unicode__(self):
            return self.article_title

    def __str__(self):
        return self.article_title












class LongArticle(models.Model):

    article_title = models.CharField(max_length=200,null=True)
    article_tagline = models.CharField(max_length=200, null=True)
    article_author = models.CharField(max_length=2000, null=True)
    article_date = models.DateTimeField('date published',null=True)
    article_id = models.IntegerField(null=True)
    article_text = models.TextField(max_length=20000,null=True)
    DEFAULT_PK =1
    metadata = models.ForeignKey(Metadata, null=True)
    article_image = models.FileField(null=True, blank=True)    # add image field to this later

    heading1 = models.CharField(max_length=250,null=True);
    paragraph1 = models.TextField(max_length=20000,null=True);

    heading2 = models.CharField(max_length=250,null=True);
    paragraph2 = models.TextField(max_length=20000,null=True);

    heading3 = models.CharField(max_length=250,null=True);
    paragraph3 = models.TextField(max_length=20000,null=True);

    heading4 = models.CharField(max_length=250,null=True);
    paragraph4 = models.TextField(max_length=20000,null=True);

    heading5 = models.CharField(max_length=250,null=True);
    paragraph5 = models.TextField(max_length=20000,null=True);

    heading6 = models.CharField(max_length=250,null=True);
    paragraph6 = models.TextField(max_length=20000,null=True);

    heading7 = models.CharField(max_length=250,null=True);
    paragraph7 = models.TextField(max_length=20000,null=True);

    heading8 = models.CharField(max_length=250,null=True);
    paragraph8 = models.TextField(max_length=20000,null=True);

    heading9 = models.CharField(max_length=250,null=True);
    paragraph9 = models.TextField(max_length=20000,null=True);

    heading10 = models.CharField(max_length=250,null=True);
    paragraph10 = models.TextField(max_length=20000,null=True);

    heading11 = models.CharField(max_length=250,null=True);
    paragraph11 = models.TextField(max_length=20000,null=True);

    heading12 = models.CharField(max_length=250,null=True);
    paragraph12 = models.TextField(max_length=20000,null=True);

    heading13 = models.CharField(max_length=250,null=True);
    paragraph13 = models.TextField(max_length=20000,null=True);

    heading14 = models.CharField(max_length=250,null=True);
    paragraph14 = models.TextField(max_length=20000,null=True);

    heading15 = models.CharField(max_length=250,null=True);
    paragraph15 = models.TextField(max_length=20000,null=True);

articles/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.db.utils import ProgrammingError
import logging
from collections import OrderedDict



from .models import Content,Metadata,LongArticle

import requests
from bs4 import BeautifulSoup
from time import localtime, strftime
import smtplib
import re



def index(request):
    print "got to views"
 
    print "got to try block"
    latest_post_list = Content.objects.order_by('-article_date')[:5]
    carousel = Content.objects.order_by('-article_date')[:3]
    older_post_list = Content.objects.order_by('-article_date')[:10]
    
    nbapreviewlist = Content.objects.filter(tags__contains='nbapreview')
    toptenlist = Content.objects.filter(tags__contains='topten')
    teambreakdown = Content.objects.filter(tags__contains='teambreakdown')

    playerankings = Content.objects.filter(tags__contains='playerankings')
    machinelearning = Content.objects.filter(tags__contains='machinelearning')
    marqueegame = Content.objects.filter(tags__contains='marqueegame')


    

    ### SCRAPING NBA STATS

    url = 'http://www.basketball-reference.com/leagues/NBA_2017_leaders.html'

    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser")

    usagerate = soup.find_all("div", {"id": "leaders_usg_pct"})

    usagerateleader = []

    for item in usagerate:
        x = item.findAll("tr")
        y = item.findAll("td")
        z = item.findAll("a")
        usagerateleader.append(z[0].text)
        usagerateleader.append(y[2].text)

    twopointfgs = soup.find_all("div", {"id": "leaders_fg2"})

    twopointfgleader = []

    for item in twopointfgs:
        x = item.findAll("tr")
        y = item.findAll("td")
        z = item.findAll("a")
        twopointfgleader.append(z[0].text)
        twopointfgleader.append(y[2].text)

    mpg = soup.find_all("div", {"id": "leaders_mp"})

    mpgleader = []

    for item in mpg:
        x = item.findAll("tr")
        y = item.findAll("td")
        z = item.findAll("a")
        mpgleader.append(z[0].text)
        mpgleader.append(y[2].text)



    url = 'http://www.rotoworld.com/headlines/nba/0/basketball-headlines'

    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser")

    news = soup.find_all("div", {"class": "pb"})

    i = 0

    newsdict = OrderedDict()

    for item in news:
        if i>2:
            break
        headline = item.findAll("a")
        report = item.findAll("p")
        print headline[0].text
        print report[0].text

        newsdict[headline[0].text] = report[0].text

        i = i + 1
    

    context = {'latest_post_list': latest_post_list, 'carousel':carousel, 'older_post_list':older_post_list, 
    'usagerateleader':usagerateleader, 'twopointfgleader':twopointfgleader,'mpgleader':mpgleader, 'newsdict':newsdict,
    'nbapreviewlist': nbapreviewlist, 'toptenlist':toptenlist, 'teambreakdown':teambreakdown,
    'playerankings':playerankings, 'machinelearning':machinelearning, 'marqueegame':marqueegame}

    
    return render(request, 'articles/new/index03.html',context)


def article(request, article_name_slug):

    context_dict = {}
    latest_post_list = Content.objects.order_by('-article_date')[:5]
    older_post_list = Content.objects.order_by('-article_date')[:4:9]
    nbapreviewlist = Content.objects.filter(tags__contains='nbapreview')
    toptenlist = Content.objects.filter(tags__contains='topten')
    teambreakdown = Content.objects.filter(tags__contains='teambreakdown')



    article = Content.objects.get(slug=article_name_slug)
    context_dict = {'article': article, 'latest_post_list': latest_post_list, 'nbapreviewlist': nbapreviewlist, 'toptenlist':toptenlist, 'teambreakdown':teambreakdown}

  
    return render(request, 'articles/new/blog-post.html', context_dict)

def standings(request):

    url = 'http://www.espn.com/nba/standings'

    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser")

    scoreboard1 = soup.find_all("tr", {"class": "standings-row"})

    easternteams = OrderedDict()


    westernteams = OrderedDict()

    
    for index,item in enumerate(scoreboard1):
        x = item.findAll("td")
        y = item.findAll("span")
        teamname = y[3].text
        #teamname = teamname[:-3]
        teamInfo = []
        teamInfo.append(teamname)
        teamInfo.append(x[1].text)
        teamInfo.append(x[2].text)
        teamInfo.append(x[3].text)
        teamInfo.append(x[4].text)
        teamInfo.append(x[5].text)
        teamInfo.append(x[6].text)
        teamInfo.append(x[7].text)
        teamInfo.append(x[8].text)
        teamInfo.append(x[9].text)
        teamInfo.append(x[10].text)
        teamInfo.append(x[11].text)
        teamInfo.append(x[12].text)
        teamInfo.append(x[13].text)

        if index<=14:
            easternteams[teamname] = teamInfo
        else:
            westernteams[teamname] = teamInfo

    nbapreviewlist = Content.objects.filter(tags__contains='nbapreview')
    toptenlist = Content.objects.filter(tags__contains='topten')
    teambreakdown = Content.objects.filter(tags__contains='teambreakdown')



    context = {'easternteams': easternteams, 'westernteams': westernteams, 'nbapreviewlist': nbapreviewlist, 'toptenlist':toptenlist, 'teambreakdown':teambreakdown}

    return render(request, 'articles/new/standings.html', context)

articles/templates/articles/new/standings.html
{% extends 'articles/new/index03.html' %}
{% block title %} NBA Standings {% endblock %} 
{% load static %}


{% block header %}
<html lang="en">
<!--[if IE 9]>  <html class="ie9" lang="en">    <![endif]-->
<!--[if IE 8]>  <html class="ie8" lang="en">    <![endif]-->
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>NBA Standings</title>

    <meta name="description" content="Electronic Responsive HTML Template is the professional responsive multi-purpose website template, based on the latest Bootstrap 3. It covers all possible web site development cases">
    <meta name="keywords" content="html5, template, css3, creative, portfolio, website, blog, personal, corporative, design, e-commerce, shop, store, design, modern, responsive, bootstrap, slider, masonry ">


    <!-- CSS -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}"                     rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/vendor/fontawesome/css/font-awesome.css' %}"                    rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/vendor/novecento/css/novecento-font.css' %}"                    rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/vendor/fancybox/css/jquery.fancybox.css' %}"            rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/vendor/fancybox/css/jquery.fancybox-buttons.css' %}"    rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/vendor/flexslider/css/flexslider.css' %}"                       rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/vendor/rs-plugin/css/settings.css' %}"                          rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/vendor/rs-plugin/css/extralayers.css' %}"                       rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/vendor/feather/css/feather.css' %}"                             rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/custom/css/style.css' %}"                                       rel="stylesheet" type="text/css" media="screen" />
      <link rel="shortcut icon" type="image/jpg" href="{% static 'img/fadeaway.jpg' %}"/>
    <!-- JS -->
    <script src="{% static 'assets/vendor/jquery/js/jquery-1.10.1.min.js' %}"                     type="text/javascript"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"                      type="text/javascript"></script>
    <script src="{% static 'assets/vendor/sticky/js/jquery.sticky.js' %}"                         type="text/javascript"></script>
    <script src="{% static 'assets/vendor/mousewheel/js/jquery.mousewheel-3.0.6.pack.js' %}"      type="text/javascript"></script>
    <script src="{% static 'assets/vendor/fancybox/js/jquery.fancybox.pack.js' %}"        type="text/javascript"></script>
    <script src="{% static 'assets/vendor/fancybox/js/jquery.fancybox-buttons.js' %}"     type="text/javascript"></script>
    <script src="{% static 'assets/vendor/fancybox/js/jquery.fancybox-media.js' %}"       type="text/javascript"></script>
    <script src="{% static 'assets/vendor/superfish/js/hoverIntent.js' %}"                        type="text/javascript"></script>
    <script src="{% static 'assets/vendor/superfish/js/superfish.js' %}"                          type="text/javascript"></script>
    <script src="{% static 'assets/vendor/superfish/js/supersubs.js' %}"                          type="text/javascript"></script>
    <script src="{% static 'assets/vendor/flickr/js/jflickrfeed.min.js' %}"                       type="text/javascript"></script>
    <script src="{% static 'assets/vendor/flexslider/js/jquery.flexslider-min.js' %}"             type="text/javascript"></script>
    <script src="{% static 'assets/vendor/flickity/js/flickity.pkgd.min.js' %}"                   type="text/javascript"></script>
    <script src="{% static 'assets/vendor/rs-plugin/js/jquery.themepunch.tools.min.js' %}"        type="text/javascript"></script>
    <script src="{% static 'assets/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js' %}"   type="text/javascript"></script>
    <script src="{% static 'assets/vendor/stellar/js/jquery.stellar.min.js' %}"                   type="text/javascript"></script>
    <script src="{% static 'assets/vendor/isotope/js/jquery.isotope.min.js' %}"                   type="text/javascript"></script>
    <script src="{% static 'assets/vendor/imagesloaded/js/imagesloaded.pkgd.min.js' %}"           type="text/javascript"></script>
    <script src="{% static 'assets/vendor/modernizr/js/modernizr.js' %}"                          type="text/javascript"></script>
    <script src="https://maps.google.com/maps/api/js?sensor=false"                 type="text/javascript"></script>
    <script src="{% static 'assets/custom/js/script.js' %}"                                       type="text/javascript"></script>


    <!-- Fonts -->
     <link href='http://fonts.googleapis.com/css?family=Oxygen:400,700' rel='stylesheet' type='text/css'>
    <!--<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,400italic' rel='stylesheet' type='text/css'>-->


    <!-- Fonts -->
     <link href='http://fonts.googleapis.com/css?family=Oxygen:400,700' rel='stylesheet' type='text/css'>


     <!-- CSS Code: Place this code in the document's head (between the 'head' tags) -->
<style>
table.GeneratedTable {
  width: 80%;
  background-color: #ffffff;
  border-collapse: collapse;
  border-width: 2px;
  border-color: #0080ff;
  border-style: solid;
  color: #000000;
}

table.GeneratedTable td, table.GeneratedTable th {
  border-width: 2px;
  border-color: #0080ff;
  border-style: solid;
  padding: 3px;
}

table.GeneratedTable thead {
  background-color: #ffffff;
}
</style>

<!-- HTML Code: Place this code in the document's body (between the 'body' tags) where the table should appear -->

<!-- Codes by Quackit.com -->




  </head>
  {% endblock %}

  {% block bodyblock %} 
  <body>

<!-- sub-top -->
    <div id="sub-top-dark">
      <div class="container">
        <div class="top-contacts">
          <div><a href="https://twitter.com/fadeawayhoops" target="_blank"><i class="fa fa-twitter"></i>@fadeawayhoops</a></div>
          <div><a href="#" target="_blank"><i class="fa fa-envelope"></i>fadeawayhoopsnba@gmail.com</a></div>
        </div>
      </div>
     </div>
    <!-- /sub-top -->

    <!-- main-top -->
    <header id="header-wrapper-mp" class="sticky-menu-dark">


      <div class="sticky-header header-dark" role="navigation">
          <div class="container mp-nav">

              <div id="site-title"><h1 class="font-accident-one-bold"><a href="/">FadeawayHoops</a></h1></div>

              <div id="mobnav-btn"><i class="fa fa-bars"></i></div>

              <nav id="main-menu" class="site-navigation primary-navigation" role="navigation">

                 <ul class="sf-menu clearfix" id="example">
                   <li><a href="{% url 'articles:index'  %}">HOME</a>



                   </li>
                    <li><a href="/standings">STANDINGS</a></li>
                    

                    <li><a>NBA PREVIEW</a>
                       <div class="mobnav-subarrow"></div>
                       <ul class="submenu">
                          {% for post in nbapreviewlist %}
                          <li><a href="/articles/{{post.slug}}" >{{post.article_title}}</a></li>
                          {% endfor %}
                       </ul>
                    </li>



                    <li class="current"><a>TOP 10 LISTS</a>
                     <div class="mobnav-subarrow"></div>
                       <ul class="submenu">
                          {% for post in toptenlist %}
                          <li><a href="/articles/{{post.slug}}" >{{post.article_title}}</a></li>
                          {% endfor %}
                       </ul>

                    </li>
                    <li class="current"><a>TEAM BREAKDOWNS</a>
                      <div class="mobnav-subarrow"></div>
                       <ul class="submenu">
                          {% for post in teambreakdownlist %}
                          <li><a href="/articles/{{post.slug}}" >{{post.article_title}}</a></li>
                          {% endfor %}
                       </ul>

                    </li>

                    

                    <!--<li><a href="#"><i class="fa fa-search"></i></a>-->
                    <!--<div class="mobnav-subarrow"></div>-->
                    <!--<ul class="submenu search-panel">-->
                    <!--<li class="">-->
                    <!--<form class="form-inline" role="form">-->
                    <!--<div class="form-group">-->
                    <!--<input type="text" class="form-control" id="exampleInputEmail2" placeholder="Search">-->
                    <!--<button type="submit" class="btn btn-default">Ok</button>-->
                    <!--</div>-->
                    <!--</form>-->
                    <!--</li>-->
                    <!--</ul>-->
                    <!--</li>-->
                 </ul>

             </nav>

            </div>
        </div>

      </header>

    <div id="content">

      <div id="blog" >

        <div class="container">

          <div class="dividewhite6"></div>

          <div id="primary" role="main">

            <h1>NBA Standings - 2016-17</h1>

  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <tr>
          <th><strong>EASTERN CONFERENCE</strong></th>
          <th>W</th>
          <th>L</th>
          <th>PCT</th>
          <th>GB</th>
          <th>HOME</th>
          <th>ROAD</th>
          <th>DIV</th>
          <th>CONF</th>
          <th>PPG</th>
          <th>OPP PPG</th>
          <th>DIFF</th>
          <th>STRK</th>
          <th>L10</th>


        </tr>
      </thead>
      <tbody>
        {% for team, info in easternteams.items %}
        <tr>
          

            {% for nba in info %}
             <td data-title="ID"> <strong>{{nba}}</strong> </td>
            {% endfor %}

            
        </tr>
        {% endfor %}


      </tbody>
    </table>

      <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
         <tr>
          <th>WESTERN CONFERENCE</th>
          <th>W</th>
          <th>L</th>
          <th>PCT</th>
          <th>GB</th>
          <th>HOME</th>
          <th>ROAD</th>
          <th>DIV</th>
          <th>CONF</th>
          <th>PPG</th>
          <th>OPP PPG</th>
          <th>DIFF</th>
          <th>STRK</th>
          <th>L10</th>


        </tr>

      </thead>
      <tbody>



        {% for team, info in westernteams.items %}
        <tr>
          

            {% for nba in info %}
             <td data-title="ID"> <strong>{{nba}}</strong> </td>
            {% endfor %}

            
        </tr>
        {% endfor %}

      </tbody>
    </table>






          </div>

        </div>

      </div>

    </div>


  {% endblock %}



    


    <!-- Back to Top -->
    <div id="back-top"><a href="#top"></a></div>
    <!-- /Back to Top -->



  </body>
</html>